name: neur299
dependencies:
- _nb_ext_conf=0.3.0=py34_0
- anaconda-client=1.6.0=py34_0
#- appnope=0.1.0=py34_0
- backports.shutil_get_terminal_size=1.0.0=py34_0
- backports_abc=0.5=py34_0
- certifi=2016.9.26=py34_0
- clyent=1.2.2=py34_0
- configparser=3.5.0=py34_0
- cycler=0.10.0=py34_0
- decorator=4.0.10=py34_1
- entrypoints=0.2.2=py34_0
- freetype=2.5.5=1
- icu=54.1=0
- ipykernel=4.5.2=py34_0
- ipython=5.1.0=py34_1
- ipython_genutils=0.1.0=py34_0
- ipywidgets=5.2.2=py34_0
- jinja2=2.8.1=py34_0
- jsonschema=2.5.1=py34_0
- jupyter=1.0.0=py34_3
- jupyter_client=4.4.0=py34_0
- jupyter_console=5.0.0=py34_0
- jupyter_contrib_core=0.3.0=py34_1
- jupyter_contrib_nbextensions=0.2.3=py34_0
- jupyter_core=4.2.1=py34_0
- jupyter_highlight_selected_word=0.0.6=py34_0
- jupyter_latex_envs=1.3.4=py34_0
- jupyter_nbextensions_configurator=0.2.3=py34_0
- libpng=1.6.22=0
- libsodium=1.0.10=0
- markupsafe=0.23=py34_2
- matplotlib=1.5.3=np111py34_1
- mistune=0.7.3=py34_1
- mkl=2017.0.1=0
- nb_anacondacloud=1.2.0=py34_0
- nb_conda=2.0.0=py34_0
- nb_conda_kernels=2.0.0=py34_0
- nbconvert=4.2.0=py34_0
- nbformat=4.2.0=py34_0
- nbgrader=0.3.1=py34_0
- nbpresent=3.0.2=py34_0
- notebook=4.3.0=py34_0
- numpy=1.11.3=py34_0
- openssl=1.0.2k=1
- pandas=0.19.2=np111py34_1
- path.py=9.0.1=py34_0
- patsy=0.4.1=py34_0
- pexpect=4.0.1=py34_0
- pickleshare=0.7.4=py34_0
- pip=9.0.1=py34_1
- prompt_toolkit=1.0.9=py34_0
- psutil=5.0.1=py34_0
- ptyprocess=0.5.1=py34_0
- pygments=2.1.3=py34_0
- pyparsing=2.1.4=py34_0
- pyqt=5.6.0=py34_1
- python=3.4.5=0
- python-dateutil=2.6.0=py34_0
- python.app=1.2=py34_4
- pytz=2016.10=py34_0
- pyyaml=3.12=py34_0
- pyzmq=16.0.2=py34_0
- qt=5.6.2=0
- qtconsole=4.2.1=py34_1
- readline=6.2=2
- requests=2.12.4=py34_0
- scikit-learn=0.18.1=np111py34_1
- scipy=0.18.1=np111py34_1
- seaborn=0.7.1=py34_0
- setuptools=27.2.0=py34_0
- simplegeneric=0.8.1=py34_1
- sip=4.18=py34_0
- six=1.10.0=py34_0
- sqlalchemy=1.1.4=py34_0
- sqlite=3.13.0=0
- statsmodels=0.6.1=np111py34_1
- terminado=0.6=py34_0
- tk=8.5.18=0
- tornado=4.4.2=py34_0
- traitlets=4.3.1=py34_0
- wcwidth=0.1.7=py34_0
- wheel=0.29.0=py34_0
- widgetsnbextension=1.2.6=py34_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - connectortools==0.1
  - dictset==0.3.1.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-contrib-core==0.3.0
  - jupyter-contrib-nbextensions==0.2.3
  - jupyter-core==4.2.1
  - jupyter-highlight-selected-word==0.0.6
  - jupyter-latex-envs==1.3.4
  - jupyter-nbextensions-configurator==0.2.3
  - mne==0.13.1
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - prompt-toolkit==1.0.9
  - pystaggrelite3==0.1.3

